name: eufemia_spacing
description: A spacing provider from DNB's design system, providing commonly used spacing components and helpers
version: 1.1.2
homepage: https://github.com/dnb-asa/eufemia_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  provider: ^4.3.1
  freezed_annotation: ^0.11.0
  flutter:
    sdk: flutter

dev_dependencies:
  json_serializable: ^3.3.0
  build_runner: ^1.10.0
  freezed: ^0.11.4
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
