name: eufemia_example
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  eufemia:
    path: ../
  device_simulator: ^0.9.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Menlo-Regular
      fonts:
        - asset: assets/fonts/Menlo-Regular.ttf

    - family: EufemiaIcons
      fonts:
        - asset: assets/fonts/EufemiaIcons.ttf

    - family: FedraSansStd
      fonts:
        - asset: assets/fonts/FedraSansStd-Bold.otf
          weight: 800
        - asset: assets/fonts/FedraSansStd-Book.otf
          weight: 400
        - asset: assets/fonts/FedraSansStd-Demi.otf
          weight: 500
        - asset: assets/fonts/FedraSansStd-Medium.otf
          weight: 600

  assets:
    - assets/icons/
