name: eufemia
description: A set of Flutter widgets and components adhering to to DNB's Eufemia design system
version: 0.6.0+1
homepage: https://dnb.no

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.4
  flutter_slidable: ^0.5.4
  meta: ^1.1.8
  shimmer: ^1.1.1
  snack: ^1.0.4
  flippable_box: ^1.0.6
  recase: ^3.0.0
  sticky_headers: ^0.1.8+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/assets/icons/
    - lib/assets/icons/tabbar/
    - lib/assets/graphics/other/
    - lib/assets/graphics/logos/
    - lib/assets/graphics/flags/
    - lib/assets/graphics/cards/
    - lib/assets/graphics/cards/programs/
    - lib/assets/graphics/cards/types/
    - lib/assets/graphics/cards/logos/

  fonts:
    - family: EufemiaIcons
      fonts:
        - asset: lib/assets/fonts/EufemiaIcons.ttf

    - family: DNB Sans
      fonts:
        - asset: lib/assets/fonts/DNB-Light.otf
          weight: 300
        - asset: lib/assets/fonts/DNB-Regular.otf
          weight: 400
        - asset: lib/assets/fonts/DNB-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/DNB-Bold.otf
          weight: 600
        - asset: lib/assets/fonts/DNB-LightItalic.otf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/DNB-RegularItalic.otf
          weight: 400
          style: italic
        - asset: lib/assets/fonts/DNB-MediumItalic.otf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/DNB-BoldItalic.otf
          weight: 600
          style: italic

    - family: DNB Mono
      fonts:
        - asset: lib/assets/fonts/DNBMono-Light.otf
          weight: 300
        - asset: lib/assets/fonts/DNBMono-Regular.otf
          weight: 400
        - asset: lib/assets/fonts/DNBMono-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/DNBMono-Bold.otf
          weight: 600
        - asset: lib/assets/fonts/DNBMono-LightItalic.otf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/DNBMono-RegularItalic.otf
          weight: 400
          style: italic
        - asset: lib/assets/fonts/DNBMono-MediumItalic.otf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/DNBMono-BoldItalic.otf
          weight: 600
          style: italic
