name: eufemia
description: A new Flutter package project.
version: 0.1.3+3
author: Arne Molland <arneolaim@gmail.com>

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.14.2
  flutter_slidable: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/assets/graphics/logos/
    - lib/assets/graphics/flags/
    - lib/assets/graphics/cards/
    - lib/assets/graphics/cards/programs/
    - lib/assets/graphics/cards/types/
    - lib/assets/graphics/cards/logos/

  fonts:
    - family: Menlo-Regular
      fonts:
        - asset: lib/assets/fonts/Menlo-Regular.ttf

    - family: EufemiaIcons
      fonts:
        - asset: lib/assets/fonts/EufemiaIcons.ttf

    - family: FedraSansStd
      fonts:
        - asset: lib/assets/fonts/FedraSansStd-Bold.otf
          weight: 800
        - asset: lib/assets/fonts/FedraSansStd-Book.otf
          weight: 400
        - asset: lib/assets/fonts/FedraSansStd-Demi.otf
          weight: 500
        - asset: lib/assets/fonts/FedraSansStd-Medium.otf
          weight: 600

    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Inter-Italic.ttf
          weight: 400
          style: italic
        - asset: lib/assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
