name: eufemia
description: A new Flutter package project.
version: 0.0.2+3
author:
homepage:

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Menlo-Regular
      fonts:
        - asset: lib/assets/fonts/Menlo-Regular.ttf

    - family: EufemiaIcons
      fonts:
        - asset: lib/assets/fonts/EufemiaIcons.ttf

    - family: FedraSansStd
      fonts:
        - asset: lib/assets/fonts/FedraSansStd-Bold.otf
          weight: 800
        - asset: lib/assets/fonts/FedraSansStd-Book.otf
          weight: 400
        - asset: lib/assets/fonts/FedraSansStd-Demi.otf
          weight: 500
        - asset: lib/assets/fonts/FedraSansStd-Medium.otf
          weight: 600
