name: eufemia
description: A new Flutter package project.
version: 0.2.3
author: Arne Molland <arneolaim@gmail.com>
homepage: https://dnb.no

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.15.0
  flutter_slidable: ^0.5.4
  meta: ^1.1.8
  shimmer: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/assets/icons/
    - lib/assets/icons/tabbar/
    - lib/assets/graphics/other/
    - lib/assets/graphics/logos/
    - lib/assets/graphics/flags/
    - lib/assets/graphics/cards/
    - lib/assets/graphics/cards/programs/
    - lib/assets/graphics/cards/types/
    - lib/assets/graphics/cards/logos/

  fonts:
    - family: Menlo-Regular
      fonts:
        - asset: lib/assets/fonts/Menlo-Regular.ttf

    - family: EufemiaIcons
      fonts:
        - asset: lib/assets/fonts/EufemiaIcons.ttf

    - family: DNB
      fonts:
        - asset: lib/assets/fonts/DNB-Light.otf
          weight: 300
        - asset: lib/assets/fonts/DNB-Regular.otf
          weight: 400
        - asset: lib/assets/fonts/DNB-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/DNB-Bold.otf
          weight: 600
