import 'package:eufemia/src/utils/icon_size.dart';

/// Flutter icons EufemiaIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EufemiaIcons
///      fonts:
///       - asset: fonts/EufemiaIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class EufemiaIcons {
  EufemiaIcons._();

  static const _kFontFam = 'EufemiaIcons';

  static const IconData add_medium =
      const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData attachment_medium =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData attachment =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData bell_medium =
      const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData bell = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData bubble_medium =
      const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData bubble = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData calendar_medium =
      const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData calendar =
      const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData check_alt_01_medium =
      const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData check_alt_01 =
      const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData check_medium =
      const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData check = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData chevron_down_medium =
      const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData chevron_down =
      const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData chevron_left_medium =
      const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData chevron_left =
      const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData chevron_right_medium =
      const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData chevron_right =
      const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData chevron_up_medium =
      const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData chevron_up =
      const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData close_medium =
      const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData error_medium =
      const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData error = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData exclamation_medium =
      const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData exclamation =
      const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData file_medium =
      const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData file = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData fullscreen_medium =
      const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData fullscreen =
      const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData hamburger_medium =
      const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData hamburger =
      const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData information_medium =
      const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData information =
      const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData link_out_medium =
      const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData link_out =
      const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData list_medium =
      const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData list = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData logout_medium =
      const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData more_medium =
      const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData more = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData pencil_medium =
      const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData pencil = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData print_medium =
      const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData print = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData question_medium =
      const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData question =
      const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData save_alt_01_medium =
      const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData save_alt_01 =
      const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData save_medium =
      const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData save = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData search_medium =
      const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData subtract_medium =
      const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData subtract =
      const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData trash_medium =
      const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData eufemia = const IconData(0xe83c, fontFamily: _kFontFam);

  /// Returns the version of the icon corresponding to the given IconSize [size].
  /// Preferably, always use the non-'medium' icons, otherwise this function
  /// returns the wrong icon.
  static getResponsiveIcon(IconSize size, IconData icon) {
    if (size == IconSize.small) {
      return icon;
    } else {
      return IconData(icon.codePoint - 1, fontFamily: _kFontFam);
    }
  }
}
