name: eufemia_palette
description: A palette provider from DNB's design system, providing colors and pre-defined palettes
version: 1.1.0+2
homepage: https://github.com/dnb-asa/eufemia_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.1
  shared_preferences: ^0.5.7
  json_annotation: ^3.0.1
  freezed_annotation: ^0.7.1
  provider: ^4.1.0
  derived_colors: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0
  build_runner: ^1.9.0
  freezed: ^0.10.7
  pedantic: ^1.9.0

flutter:
