name: eufemia_palette
description: A palette provider from DNB's design system, providing colors and pre-defined palettes
version: 1.1.3
homepage: https://github.com/dnb-asa/eufemia_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  shared_preferences: ^0.5.8
  json_annotation: ^3.0.1
  freezed_annotation: ^0.11.0
  provider: ^4.3.1
  derived_colors: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0
  build_runner: ^1.10.0
  freezed: ^0.11.4
  pedantic: ^1.9.0

flutter:
