include: package:pedantic/analysis_options.yaml

linter:
  rules:
    # - public_member_api_docs
    - type_annotate_public_apis
analyzer:
  strong-mode:
    implicit-dynamic: true
    implicit-casts: true

  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    # allow having TODOs in the code
    todo: ignore
    # Ignore analyzer hints for updating pubspecs when using Future or
    # Stream and not importing dart:async
    # Please see https://github.com/flutter/flutter/pull/24528 for details.
    sdk_version_async_exported_from_core: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
