name: eufemia_typography
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/dnb-asa/eufemia_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  freezed_annotation: ^0.7.1
  derived_colors: ^0.2.4

  # Eufemia
  eufemia_palette:
    path: ../eufemia_palette

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:
  freezed: ^0.10.7
  pedantic: ^1.9.0

  flutter_test:
    sdk: flutter

flutter:
