name: eufemia_typography
description: A provider of typography and text-related utilities and components from DNB's design system
version: 1.1.3
homepage: https://github.com/dnb-asa/eufemia_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  freezed_annotation: ^0.7.1
  derived_colors: ^0.2.4

  # Eufemia
  eufemia_palette: ">=1.0.0 <2.0.0"

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:
  freezed: ^0.10.7
  pedantic: ^1.9.0

  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: DNB Sans
      fonts:
        - asset: lib/fonts/DNB-Light.otf
          weight: 300
        - asset: lib/fonts/DNB-Regular.otf
          weight: 400
        - asset: lib/fonts/DNB-Medium.otf
          weight: 500
        - asset: lib/fonts/DNB-Bold.otf
          weight: 600
        - asset: lib/fonts/DNB-LightItalic.otf
          weight: 300
          style: italic
        - asset: lib/fonts/DNB-RegularItalic.otf
          weight: 400
          style: italic
        - asset: lib/fonts/DNB-MediumItalic.otf
          weight: 500
          style: italic
        - asset: lib/fonts/DNB-BoldItalic.otf
          weight: 600
          style: italic

    - family: DNB Mono
      fonts:
        - asset: lib/fonts/DNBMono-Light.otf
          weight: 300
        - asset: lib/fonts/DNBMono-Regular.otf
          weight: 400
        - asset: lib/fonts/DNBMono-Medium.otf
          weight: 500
        - asset: lib/fonts/DNBMono-Bold.otf
          weight: 600
        - asset: lib/fonts/DNBMono-LightItalic.otf
          weight: 300
          style: italic
        - asset: lib/fonts/DNBMono-RegularItalic.otf
          weight: 400
          style: italic
        - asset: lib/fonts/DNBMono-MediumItalic.otf
          weight: 500
          style: italic
        - asset: lib/fonts/DNBMono-BoldItalic.otf
          weight: 600
          style: italic
