name: eufemia
description: A set of Flutter widgets and reusable UI components from DNB's design system
version: 1.0.5
homepage: https://dnb.no

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.4
  flutter_slidable: ^0.5.4
  meta: ^1.1.8
  shimmer: ^1.1.1
  snack: ^1.0.4
  flippable_box: ^1.0.6
  recase: ^3.0.0
  sticky_headers: ^0.1.8+1

  # Eufemia dependencies
  eufemia_palette: ">=1.1.2 <2.0.0"
  eufemia_components: ">=1.1.5 <2.0.0"
  eufemia_spacing: ">=1.1.1 <2.0.0"
  eufemia_typography: ">=1.1.3 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
