name: eufemia_components
description: A collection of commonly used UI components from DNB's design system
version: 1.1.1+3
homepage: https://github.com/dnb-asa/eufemia_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^0.5.4
  flutter_svg: ^0.17.4
  path_drawing: ^0.4.1
  shimmer: ^1.1.1
  flippable_box: ^1.0.6
  recase: ^3.0.0
  snack: ^1.0.4

  http: ^0.12.1
  shared_preferences: ^0.5.7
  json_annotation: ^3.0.1
  freezed_annotation: ^0.7.1
  provider: ^4.1.0
  derived_colors: ^0.2.4

  eufemia_palette: ^1.1.0
  eufemia_typography: ^1.1.1
  eufemia_spacing: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0
  build_runner: ^1.9.0
  freezed: ^0.10.7
  pedantic: ^1.9.0

flutter:
  assets:
    - lib/assets/icons/
    - lib/assets/icons/tabbar/
    - lib/assets/graphics/other/
    - lib/assets/graphics/logos/
    - lib/assets/graphics/flags/
    - lib/assets/graphics/cards/
    - lib/assets/graphics/cards/programs/
    - lib/assets/graphics/cards/types/
    - lib/assets/graphics/cards/logos/

  fonts:
    - family: EufemiaIcons
      fonts:
        - asset: lib/assets/EufemiaIcons.ttf
