name: Dart CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev"
      - name: Install dependencies
        run: flutter packages get
      - name: Analyze
        run: flutter analyze
        
  deploy:
    runs-on: ubuntu-latest
    
    container:
      image:  google/dart:latest
      
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: Setup credentials
      run: | 
        mkdir -p ~/.pub-cache 
        cat <<EOF > ~/.pub-cache/credentials.json
        {
          "accessToken":"${{ secrets.PUB_OAUTH_ACCESS_TOKEN }}",
          "refreshToken":"${{ secrets.PUB_OAUTH_REFRESH_TOKEN }}",
          "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
          "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
          "expiration": 1570721159347
        }
        EOF
    - name: Publish package
      run: pub publish -f
