name: Dart CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - name: Install dependencies
        run: flutter packages get
      - name: Analyze
        run: flutter analyze
