name: Dart CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: cirrusci/flutter:dev

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo flutter packages get
      - name: Analyze
        run: flutter analyze
